name: Fly Deploy
on:
  pull_request:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c fly_test.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_TEST }}
