name: Package Application with Pyinstaller

on:
  release:
    types: [published, edited]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package Application
        uses: eric2788/pyinstaller-build@master
        with:
          main: src/gui
          artifact: AIDApp
          use-dependencies: true
          no-console: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AIDApp
          path: dist
