name: Run pytest on the code

on:
  push:
    paths:
      - "src/**"
      - "!src/translations"
  pull_request:
    branches:
      - "main"
      - "staging"
  workflow_dispatch:
        
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libgl1-mesa-dev
        python -m pip install --upgrade pip
        pip install pytest-cov black
        pip install .
    - name: Format code with black
      run: |
        black .
    - name: Test with pytest
      run: |
        pytest
